<a href="https://colab.research.google.com/github/pavankumarsai18/learn_ml/blob/main/learn_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import time





In [ ]:
def time_it(func, args):
  def helper(args):
    start = time.time()
    func(args)
    end = time.time()
    print(f"function took {end - start} seconds")
  return helper


def measure_mult_time_diff(num_elements):
  python_list = [ num for num in range(num_elements) ]
  numpy_list  = np.array([num for num in range(num_elements)])

  np_start = time.time()
  numpy_list *= 2
  np_end   = time.time()

  py_start = time.time()
  for idx in range(len(python_list)):
    python_list[idx] *= 2
  py_end   = time.time()
  return {"np": (np_end - np_start), "py": (py_end - py_start)}



for x in range(1, 50):
  num_items = 2**x
  time_result = measure_mult_time_diff(num_items)
  print(f"num_items: 2^{x} np: {time_result['np']} sec, py: {time_result['py']} sec")

In [ ]:

np_arr = np.array([[1, 2, 3], [4, 5, 6]])


# This is how you print the shape of array
print(f"shape of np_arr {np_arr.shape}")

# Shape is 2, 3 we can reshape the array as long
# as the number of elements are the same

np_arr = np.reshape(np_arr, (3, 2))

print(f"np_arr after reshaping to {np_arr.shape} is:\n {np_arr}")

np_arr = np.reshape(np_arr, (6, 1))
print(f"np_arr after reshaping to {np_arr.shape} is:\n {np_arr}")

np_arr = np.reshape(np_arr, (1, 6))
print(f"np_arr after reshaping to {np_arr.shape} is:\n {np_arr}")

np_arr = np.reshape(np_arr, (2, 3))
print(f"np_arr after reshaping to {np_arr.shape} is:\n {np_arr}")



shape of np_arr (2, 3)
np_arr after reshaping to (3, 2) is:
 [[1 2]
 [3 4]
 [5 6]]
np_arr after reshaping to (6, 1) is:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
np_arr after reshaping to (1, 6) is:
 [[1 2 3 4 5 6]]
np_arr after reshaping to (2, 3) is:
 [[1 2 3]
 [4 5 6]]


In [ ]:
np_arr = np.array([[1, 2, 3], [4, 5, 6]])

# axis = 0 --> is along  column
np.sum(np_arr, axis=0)

# axis = 1 --> along rows
np.mean(np_arr, axis=1)


array([2., 5.])

In [ ]:
# arange create n items

num_elements = 1_000_000
np_arr = np.arange(num_elements)

print(np_arr)

[     0      1      2 ... 999997 999998 999999]
